package com.example.tripapp2.domain.entities

enum class Category(val id: Int, val slug: String, val nameRU: String) {
    DEFAULT(-1, "", ""),
    AIRPORTS(123, "airports", "Аэропорты"),
    AMUSEMENT(89, "amusement", "Развлечения"),
    ANIMAL_SHELTERS(114, "animal-shelters", "Питомники"),
    ANTI_CAFE(17, "anticafe", "Антикафе"),
    ART_CENTERS(113, "art-centers", "Арт-центры"),
    ART_SPACE(130, "art-space", "Арт-пространства"),
    ATTRACTIONS(51, "attractions", "Достопримечательности"),
    BAR(19, "bar", "Бары и пабы"),
    BREWERY(134, "brewery", "Пивоварня"),
    BRIDGE(58, "bridge", "Мосты"),
    BUSINESS(112, "business", "Бизнес-центры"),
    CAR_WASHES(94, "car-washes", "Автомойки"),
    CATS(97, "cats", "Кошачий питомник"),
    CHURCH(63, "church", "Церкви"),
    CINEMA(49, "cinema", "Кинотеатры"),
    CLUBS(26, "clubs", "Клубы"),
    COMEDY_CLUB(135, "comedy-club", "Камеди клаб"),
    CONCERT_HALL(28, "concert-hall", "Концертные залы"),
    COWORKING(101, "coworking", "Коворкинги"),
    CULTURE(45, "culture", "Дома культуры"),
    DANCE_STUDIO(124, "dance-studio", "Танцевальные студии"),
    DOGS(98, "dogs", "Собачий питомник"),
    EDUCATION_CENTERS(71, "education-centers", "Учебные заведения"),
    FOUNTAIN(57, "fountain", "Фонтаны"),
    HANDMADE(110, "handmade", "HandMade"),
    HOMESTEADS(69, "homesteads", "Усадьбы"),
    HOSTELS(104, "hostels", "Хостелы"),
    INN(105, "inn", "Гостиницы и отели"),
    KIDS(102, "kids", "Детям"),
    LIBRARY(50, "library", "Библиотеки"),
    METRO(92, "metro", "Метро"),
    MONASTERY(66, "monastery", "Монастыри"),
    MUSEUMS(42, "museums", "Музеи и галереи"),
    OBSERVATORY(46, "observatory", "Обсерватории"),
    OTHER(111, "other", "Прочее"),
    PALACE(67, "palace", "Дворцы"),
    PARK(59, "park", "Парки (Интересные места, Отдых)"),
    PHOTO_PLACES(91, "photo-places", "Фотоместа (Фотография)"),
    PRIRODNYJ_ZAPOVEDNIK(137, "prirodnyj-zapovednik", "Природный заповедник"),
    QUEST_ROOM(139, "questroom", "Квесты"),
    RECREATION(140, "recreation", "отдых"),
    RESTAURANTS(15, "restaurants", "Рестораны и кафе"),
    RYNOK(136, "rynok", "Рынок"),
    SALONS(90, "salons", "Красота и здоровье"),
    SHOPS(108, "shops", "Магазины"),
    SIGHTS(53, "sights", "Интересные места"),
    STABLE(95, "stable", "Конюшни, конные клубы"),
    STATION(93, "station", "Вокзалы"),
    STRIP_CLUB(133, "strip-club", "Стрип-клуб"),
    SUBURB(70, "suburb", "Загородный отдых"),
    SYNAGOGUE(65, "synagogue", "Синагоги"),
    TEMPLE(62, "temple", "Храмы"),
    THEATRE(48, "theatre", "Театры"),
    WORKSHOPS(127, "workshops", "Мастерские");
}
